spring:
  application:
    name: API-Gateway

#Api Gateway Config
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: OrderService
              uri: lb://ORDERSERVICE
              predicates:
                - Path=/orders/**
              filters:
                - name: LoggingOrdersFilter
            - id: InventoryService
              uri: lb://INVENTORYSERVICE
              predicates:
                - Path=/inventory/**

##server port
server:
  port: 8084

#Eureka Client Config
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8083/eureka