management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

resilience4j:
  retry:
    configs:
      default:
        maxRetryAttempts: 3
        waitDuration: 100ms
    instances:
      inventoryRetry:
        baseConfig: default
        waitDuration: 200ms
  ratelimiter:
    instances:
      inventoryRateLimiter:
        limitForPeriod: 10
        limitRefreshPeriod: 1s
        timeOutDuration: 10
  circuitbreaker:
    instances:
      inventoryCircuitBreaker:
        register-health-indicator: true
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10000
        permitted-number-of-calls-in-half-open-state: 5
        sliding-window-type: COUNT_BASED
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
