resilience4j:
  retry:
    instances:
      inventoryRetry:
        maxRetryAttempts: 3
        waitDuration: 100ms
  ratelimiter:
    instances:
      inventoryRateLimiter:
        limitForPeriod: 10
        limitRefreshPeriod: 1s
        timeOutDuration: 10s